-- AlterTable
ALTER TABLE "DailyActivity" ALTER COLUMN "tanggal" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "tanggal" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Streak" ALTER COLUMN "tanggal" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "tanggal" SET DATA TYPE TIMESTAMPTZ;
